markdown: rdiscount
permalink: /:title/
url: http://nicholegit.github.io
name: 杨巍
author: nicholegit
qq: 2762481669 
email: 2762481669@qq.com
duoshuo: nicholegit
beian: 
cnzz: 1253802308
weibo: 
github: 
pygments: true
paginate: 20
truncate: true
about: "杨巍(nichole)"
